<a href="https://colab.research.google.com/github/MabineS/myweb/blob/main/Copy_of_l01c01_introduction_to_colab_and_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [ ]:
Fruit= np.array(['Apple','banana','Grapes','Orange','Guava'])

In [ ]:
Fruit

array(['Apple', 'banana', 'Grapes', 'Orange', 'Guava'], dtype='<U6')

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(7)#arange()

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
np.arange(16,30)
#start number

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(16,30,2)#COUNTING USING +2 STEP METHOD
#16 STARTING VALUE #30 STOPPING VALUE

array([16, 18, 20, 22, 24, 26, 28])

In [3]:
np.linspace(10,46,16)

array([10. , 12.4, 14.8, 17.2, 19.6, 22. , 24.4, 26.8, 29.2, 31.6, 34. ,
       36.4, 38.8, 41.2, 43.6, 46. ])

In [7]:
B=np.linspace(0,20,11)
#eleven spaced values starting from 0 to 20
#dtype checks which data type it is
print(B.dtype)

float64


In [9]:
np.linspace(0,20,11,dtype=int)
#it will display integer values because of dtype=int

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
#if else
age= 5
if age>= 18 :
  print("You can vote")
else :
  print("You cannot vote")

You cannot vote


In [11]:
password = "Kopinator123"
if password == 'Kopinator123':
  print("access granted")
else:
  print("access denied!")


access granted


In [12]:
age=int(input("Enter your age:"))
if age<13:
  print("You are a kid")
elif age<20:
  print("You are a teenaager")
elif age<60:
  print("You are an adult")
else : print("you are a senior")

Enter your age:6
You are a kid
